### ISSUE TITLE
HttpUrl should allow host to start with digits

### ISSUE THREAD

**Issue by mykmelez** [andreasgal/j2me.js#990] opened 2015-01-30 23:23 UTC
Per @yxl over in https://github.com/andreasgal/j2me.js/pull/834#issuecomment-69530802:
> The bug with current implementation is that it doesn't allow the host to start with digits, such as 123.domain. But from wikipedia and RFC 1123, it should be allowed.
>
> The old version (mr2-rel-b23) implementation doesn't have such issue, however it isn't capable of checking and recognizing ipv6 URLs and couldn't pass tests of TestUrl.java

We didn't end up merging that pull request, since it introduces other issues. But we should still fix this issue in the current codebase.

**Comment by marco-c** [comment] 2015-01-31 12:26
Duplicate of https://github.com/andreasgal/j2me.js/issues/185

**Closed by marco-c** 2015-01-31 12:26 UTC
Labels: duplicate
