### ISSUE TITLE
missing native com/sun/cldc/isolate/Isolate.stop

### ISSUE THREAD

**Issue by mykmelez** [andreasgal/j2me.js#527] opened 2014-11-03 16:43 UTC
I saw this while testing a midlet a few days ago:

> "Attempted to invoke missing native:" "com/sun/cldc/isolate/Isolate.stop.(II)V"
> "java.lang.IllegalStateException: getID"
> " - java/lang/Throwable.<init>(), bci=8"
> " - java/lang/Exception.<init>(), bci=5"
> " - java/lang/RuntimeException.<init>(), bci=5"
> " - java/lang/IllegalStateException.<init>(), bci=5"
> " - com/sun/midp/midletsuite/MIDletSuiteImpl.guaranteeMIDletSuiteLocked(), bci=15"
> " - com/sun/midp/midletsuite/MIDletSuiteImpl.getID(), bci=6"
> " - javax/microedition/rms/RecordStore.isRecordStoreOwner(), bci=11"
> " - javax/microedition/rms/RecordStore.checkWritable(), bci=4"
> " - javax/microedition/rms/RecordStore.addRecord(), bci=8"
> [midlet-specific classes]

I haven't been able to reproduce it (and don't remember how now); so it seems rare, and it could have been a product of the modified state of my tree at the time. But let's keep an eye out for it.

**Comment by marco-c** [comment] 2015-01-22 12:50
Duplicate of #744.

**Closed by marco-c** 2015-01-22 12:50 UTC
Labels: duplicate
